automation:


  - id: entry_light_on_when_arriving_home
    alias: "Entry light on when someone gets home"
    initial_state: True
    trigger:
      platform: state
      entity_id: group.all_devices
      from: 'not_home'
      to: 'home'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      service: switch.turn_on
      entity_id: switch.entry_light_switch

  - alias: 'Jason home notification'
    trigger:
      platform: state
      entity_id: device_tracker.jason_phone
      from: 'not_home'
      to: 'home'
    action:
      service: notify.pushbullet
      data:
        title: 'Jason is home'
        message: 'Jason is home'

  - alias: 'Jason away notification'
    trigger:
      platform: state
      entity_id: device_tracker.jason_phone
      from: 'home'
      to: 'not_home'
    action:
      service: notify.pushbullet
      data:
        title: 'Jason is away'
        message: 'Jason is away'

  - id: night_dark_theme
    alias: 'Change to a dark theme at night'
    trigger:
      - platform: sun
        event: sunset
    action:
      service: frontend.set_theme
      data:
        name: midnight

  - id: day_light_theme
    alias: 'Change to a light theme during the day'
    trigger:
      - platform: sun
        event: sunrise
    action:
      service: frontend.set_theme
      data:
        name: default


  - id: night_guest_room_on
    alias: 'Turn the guest room lamp on at night'
    trigger:
      - platform: sun
        event: sunset
    action:
      - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_on
        entity_id: switch.guest_room_lamp

  - id: night_guest_room_off
    alias: 'Turn the guest room lamp off about an hour after sunset'
    trigger:
      - platform: sun
        event: sunset
    action:
      - delay: "01:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_off
        entity_id: switch.guest_room_lamp

  - id: night_porch_on
    alias: 'Turn the porch light on at night'
    trigger:
      - platform: sun
        event: sunset
    action:
      - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_on
        entity_id: switch.front_porch_switch

  - id: night_porch_off
    alias: 'Turn the porch light off at night'
    trigger:
      - platform: time
        at: '23:30:00'
    action:
      - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_off
        entity_id: switch.front_porch_switch

  - id: morning_porch_on
    alias: 'Turn the porch light on in the morning'
    trigger:
      - platform: time
        at: '05:45:00'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_on
        entity_id: switch.front_porch_switch

  - id: morning_porch_off
    alias: 'Turn the porch light off in the morning'
    trigger:
      - platform: sun
        event: sunrise
    action:
      - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_off
        entity_id: switch.front_porch_switch
