homeassistant:
  customize:
    sensor.dark_sky_temperature:
      friendly_name: Temp

    sensor.dark_sky_minutely_summary:
      friendly_name: Right Now

    sensor.dark_sky_hourly_summary:
      friendly_name: Today

sensor:
  - platform: darksky
    api_key: !secret darksky_key
    update_interval:
      hours: 1
    monitored_conditions:
      - summary
      - temperature
      - minutely_summary
      - hourly_summary

#      - summary
#      - icon
#      - nearest_storm_distance
