device_tracker:
  - platform: bluetooth_tracker
    interval_seconds: 5
    consider_home: 180

  - platform: tplink
    host: 10.0.1.2
    username: !secret archer_username
    password: !secret archer_password
    track_new_devices: false
    new_device_defaults:
      track_new_devices: false

group:
  jason:
    name: Jason
    entities:
      - device_tracker.jason_phone
      - device_tracker.jason_phone_bt

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 25
    icon: mdi:account-multiple

homeassistant:
  customize:
    group.jason:
      entity_picture: /local/jason-192x192.jpg
