device_tracker:

  - platform: netgear
    host: 10.0.1.1
    username: !secret orbi_username
    password: !secret orbi_password

group:
  jason:
    name: Jason
    entities:
      - device_tracker.jason_phone

  kim:
    name: Kim
    entities:
      - device_tracker.kim_phone

  abby:
    name: Abby
    entities:
      - device_tracker.abby_phone

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 25
    icon: mdi:account-multiple

homeassistant:
  customize:
    group.jason:
      entity_picture: /local/jason-192x192.jpg
    group.kim:
      entity_picture: /local/kim-192x192.jpg
    group.abby:
      entity_picture: /local/abby-192x192.jpg
