device_tracker:


#### not working; might have to try "ping" platform instead
  - platform: netgear
    #url: http://www.orbilogin.com
    username: !secret orbi_username
    password: !secret orbi_password
    accesspoints:
      - 9C:3D:CF:2C:A4:A0
      - 9C:3D:CF:2C:A5:7C
    devices:
       #### jason's phone
       0e:4f:e9:31:bd:a0

group:
  jason:
    name: Jason
    entities:
      - device_tracker.jason_phone

  kim:
    name: Kim
    entities:
      - device_tracker.kim_phone

  abby:
    name: Abby
    entities:
      - device_tracker.abby_phone

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 25
    icon: mdi:account-multiple

homeassistant:
  customize:
    group.jason:
      entity_picture: /local/jason-192x192.jpg
    group.kim:
      entity_picture: /local/kim-192x192.jpg
    group.abby:
      entity_picture: /local/abby-192x192.jpg
