#### get your icons from https://materialdesignicons.com/cheatsheet
input_boolean:
  vacation_mode:
    name: Turn on vacation mode
    icon: mdi:beach

#### randomization techniques I've found; note that some do nice stuff like integer
#### conversion, and some do nice stuff like padding with zeroes.  One uses "{{" and "}}"
#### as template delimiters, and one uses "{{-" and "-}}".  Needless to say, I'm not sure what
#### the perfectly "right" way is to do this...

#### delay of 00:01:00 to 02:59:00
####   delay: '{{ (range(0, 2)|random|int) }}:{{ (range(1, 59)|random|int) }}:00'
#### delay of 00:01:00 to 00:09:00
####   delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
####
#### Apparently, "offset" doesn't work the way "delay" does; you can't use the templating syntax.
#### offset of -00:15:00 to -00:30:00:
####   offset: "-00:{{- ((range(15,30) | random) ~ '').rjust(2, '0') -}}:00"  DOES NOT WORK!
#### But you could just offset by one hour and then delay by 30-45 minutes to get the same effect

automation:
  - id: morning_guest_room_on
    alias: 'Turn the guest room lamp on in the morning'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    trigger:
      - platform: sun
        event: sunrise
        offset: "-01:00:00"
    action:
      - delay: "00:{{- ((range(30,45) | random) ~ '') -}}:00"
      - service: switch.turn_on
        entity_id: switch.sonoff4

  - id: morning_guest_room_off
    alias: 'Turn the guest room lamp off in the morning'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    trigger:
      - platform: sun
        event: sunrise
    action:
      - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_off
        entity_id: switch.sonoff4

  - id: night_family_room_lamp_on
    alias: 'Turn the family room lamp on at night'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    trigger:
      - platform: sun
        event: sunset
    action:
      - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_on
        entity_id: switch.family_room_lamp_switch

  - id: night_family_room_lamp_off
    alias: 'Turn the family room lamp off at night'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    trigger:
      - platform: time
        at: '19:30:00'
    action:
      - delay: "00:{{- ((range(1,9) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_off
        entity_id: switch.family_room_lamp_switch

  - id: evening_living_room_on
    alias: 'Turn the living room lamp on in the evening'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    trigger:
      - platform: time
        at: '18:50:00'
    action:
      - delay: "00:{{- ((range(1,20) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_on
        entity_id: switch.living_room_lamp

  - id: evening_living_room_off
    alias: 'Turn the living room lamp off at night'
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    trigger:
      - platform: time
        at: '22:00:00'
    action:
      - delay: "00:{{- ((range(10,20) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_off
        entity_id: switch.living_room_lamp

  - id: night_nates_room_on
    alias: "Turn Nate's bedroom lamp on at night"
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    trigger:
      - platform: time
        at: '21:00:00'
    action:
      - delay: "00:{{- ((range(1,30) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_on
        entity_id: switch.nates_room

  - id: night_nates_room_off
    alias: "Turn Nate's bedroom lamp off at night"
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    trigger:
      - platform: time
        at: '22:15:00'
    action:
      - delay: "00:{{- ((range(1,30) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_off
        entity_id: switch.nates_room

  - id: night_jasons_lamp_on
    alias: "Turn Jason's bedroom lamp on at night"
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    trigger:
      - platform: time
        at: '21:30:00'
    action:
      - delay: "00:{{- ((range(1,30) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_on
        entity_id: switch.sonoff2

  - id: night_jasons_lamp_off
    alias: "Turn Jason's bedroom lamp off at night"
    condition:
      condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
    trigger:
      - platform: time
        at: '22:15:00'
    action:
      - delay: "00:{{- ((range(1,30) | random) ~ '').rjust(2, '0') -}}:00"
      - service: switch.turn_off
        entity_id: switch.sonoff2
